// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClpKBbAgLBRR0fB36W9LVSAFWEBwTCNMk',
    appId: '1:425809765981:web:a0fe18b07a5763354fcfb4',
    messagingSenderId: '425809765981',
    projectId: 'fir-flutter-codelab-544de',
    authDomain: 'fir-flutter-codelab-544de.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-544de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp2bJmwUHGW6A3_tHR2SqorUNaCz_8XmI',
    appId: '1:425809765981:android:fe0d6b943a92f5534fcfb4',
    messagingSenderId: '425809765981',
    projectId: 'fir-flutter-codelab-544de',
    storageBucket: 'fir-flutter-codelab-544de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFi2fuPi0yZeH0LiPjAUxQuwD-GUwVNTs',
    appId: '1:425809765981:ios:0902fb37af5362124fcfb4',
    messagingSenderId: '425809765981',
    projectId: 'fir-flutter-codelab-544de',
    storageBucket: 'fir-flutter-codelab-544de.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFi2fuPi0yZeH0LiPjAUxQuwD-GUwVNTs',
    appId: '1:425809765981:ios:0902fb37af5362124fcfb4',
    messagingSenderId: '425809765981',
    projectId: 'fir-flutter-codelab-544de',
    storageBucket: 'fir-flutter-codelab-544de.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
